import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ManagerPageNavbar from "../components/navbars/manager-nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Manager Dashboard",
  description: "Generated by create next app",
};

export default function Layout({
  children,
  players,
  notifications,
  leagues,
  play
}: Readonly<{
  children: React.ReactNode;
  players: React.ReactNode;
  notifications: React.ReactNode;
  leagues: React.ReactNode;
  play: React.ReactNode;
}>) {
  return (
    <ManagerPageNavbar>
      {children}
      {players}
      {notifications}
      {leagues}
      {play}
    </ManagerPageNavbar>
  );
}
