import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ManagerPageNavbar from "../components/navbars/manager-nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Manager Dashboard",
  description: "Generated by create next app",
};

export default function ManagerLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body className={`${inter.className} bg-gray-300 overflow-y-hidden`} >
        <ManagerPageNavbar />
        {children}
      </body>
    </html>
  );
}
