import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ManagerPageNavbar from "../components/navbars/manager-nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Manager Dashboard",
  description: "Generated by create next app",
};

export default function Layout({
  children,
  players,
  notifications,
  leagues,
  play,
  statistics,
}: Readonly<{
  children: React.ReactNode;
  players: React.ReactNode;
  notifications: React.ReactNode;
  leagues: React.ReactNode;
  play: React.ReactNode;
  statistics: React.ReactNode;
}>) {
  return (
    <ManagerPageNavbar>
      <div className="p-4">
        {children}
        <div
          className="grid grid-cols-12 grid-rows-12 gap-1 pt-2"
          style={{ height: "80vh" }}
        >
          {leagues}
          {players}
          {notifications}
          {statistics}
          {play}
        </div>
      </div>
    </ManagerPageNavbar>
  );
}
